# Generated by Django 2.2.7 on 2019-11-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSystems',
            fields=[
                ('solarSystemID', models.IntegerField(primary_key=True, serialize=False)),
                ('solarSystemName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystemJumps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromSolarSystemID', models.IntegerField()),
                ('toSolarSystemID', models.IntegerField()),
            ],
            options={
                'unique_together': {('fromSolarSystemID', 'toSolarSystemID')},
            },
        ),
    ]
