# Generated by Django 3.0.1 on 2020-01-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsystemjumps',
            name='fromConstellationID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarsystemjumps',
            name='fromRegionID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarsystemjumps',
            name='toConstellationID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarsystemjumps',
            name='toRegionID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarsystems',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarsystems',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarsystems',
            name='z',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
