version: "3"
services:
    web:
        build: .
        ports:
            - "8000:8000"
        container_name: blue-donut
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:aimsucks.space"
            - "traefik.docker.network=web"
            - "traefik.port=80"
        networks:
            - web
