version: "3"
services:
    django:
        build: .
        ports:
            - "8000:8000"
        container_name: blue-donut
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:bluedonut.space"
            - "traefik.docker.network=web"
            - "traefik.port=80"
        networks:
            - web

networks:
    web:
        external: true
