version: "3.7"
services:
    app:
        build: .
        container_name: django-gunicorn
        restart: always
        env_file:
            - django.env
        ports:
            - "8000:8000"
        command: "gunicorn --workers=2 --bind=0.0.0.0:8000 blue_donut.wsgi:application"

    nginx:
        image: nginx:latest
        container_name: ngx
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - app
