# Generated by Django 3.0.3 on 2020-02-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_constellation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='map.Constellation')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('x', models.DecimalField(decimal_places=10, max_digits=35)),
                ('y', models.DecimalField(decimal_places=10, max_digits=35)),
                ('z', models.DecimalField(decimal_places=10, max_digits=35)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Constellation')),
                ('gates', models.ManyToManyField(related_name='gate_set', through='map.Gate', to='map.System')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Region')),
            ],
        ),
        migrations.AddField(
            model_name='gate',
            name='from_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='map.Region'),
        ),
        migrations.AddField(
            model_name='gate',
            name='from_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='map.System'),
        ),
        migrations.AddField(
            model_name='gate',
            name='to_constellation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='map.Constellation'),
        ),
        migrations.AddField(
            model_name='gate',
            name='to_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='map.Region'),
        ),
        migrations.AddField(
            model_name='gate',
            name='to_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='map.System'),
        ),
        migrations.AddField(
            model_name='constellation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='gate',
            unique_together={('from_system', 'to_system')},
        ),
    ]
