# Generated by Django 3.0.3 on 2020-02-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('structureID', models.IntegerField(primary_key=True, serialize=False)),
                ('ownerID', models.BigIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fromSolarSystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='map.System')),
                ('toSolarSystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='map.System')),
            ],
        ),
    ]
