# Generated by Django 3.0.3 on 2020-02-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bridge',
            old_name='fromSolarSystem',
            new_name='from_system',
        ),
        migrations.RenameField(
            model_name='bridge',
            old_name='structureID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='bridge',
            old_name='ownerID',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='bridge',
            old_name='toSolarSystem',
            new_name='to_system',
        ),
    ]
