# Generated by Django 2.2.7 on 2019-11-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsiblexJumpGates',
            fields=[
                ('structureID', models.IntegerField(primary_key=True, serialize=False)),
                ('fromSolarSystemID', models.IntegerField()),
                ('toSolarSystemID', models.IntegerField()),
            ],
        ),
    ]
