# Generated by Django 3.0.1 on 2020-01-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_bridges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblexjumpgates',
            name='ownerID',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
