# Generated by Django 3.0.1 on 2020-01-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump_bridges', '0002_ansiblexjumpgates_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblexjumpgates',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
