# Generated by Django 3.0.1 on 2020-01-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveuser',
            name='scope_read_location',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eveuser',
            name='scope_read_structures',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eveuser',
            name='scope_search_structures',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eveuser',
            name='scope_write_waypoint',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
