# Generated by Django 3.0.1 on 2020-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0002_auto_20200117_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveuser',
            name='alliance_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eveuser',
            name='corporation_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
