# Generated by Django 3.0.1 on 2020-01-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0003_auto_20200122_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveuser',
            name='esi_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
