# Generated by Django 3.0.3 on 2020-02-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
