# Generated by Django 3.0.3 on 2020-02-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0002_eveuser_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eveuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='eveuser',
            name='character_id',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
