# Generated by Django 3.0.3 on 2020-02-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0003_auto_20200207_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eveuser',
            name='active',
        ),
    ]
