# Generated by Django 3.0.3 on 2020-02-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0004_remove_eveuser_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVEData',
        ),
    ]
