# Generated by Django 3.0.3 on 2020-02-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20200210_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularsystems',
            name='popular',
            field=models.CharField(default='["","","","",""]', max_length=8192),
        ),
    ]
